export { Nav } from './Nav';
export { Hero } from './Hero';
export { About } from './About';
export { Projects } from './Projects';
export { Skills } from './Skills';
export { Experience } from './Experience';
export { Contact } from './Contact';
export { Footer } from './Footer';
export { Reveal } from './Reveal';
